version: '2'
services:
    myhipster-app:
        image: myhipster
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://myhipster-mariadb:3306/myhipster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    myhipster-mariadb:
        extends:
            file: mariadb.yml
            service: myhipster-mariadb
